Develop
rostikkkk2/bookstore-rg pull request #1
Opened 2019-01-20 11:00 UTC by rostikkkk2

2019-01-31 18:44 UTC, dzemlianoi-double commented on Gemfile
> +gem 'pry-rails'
dev

2019-01-31 18:44 UTC, dzemlianoi-double commented on app/controllers/books_controller.rb
> +    @books = Book.all
Book.find_by(id: params[:id])

2019-01-31 18:44 UTC, dzemlianoi-double commented on app/controllers/categories_controller.rb
> +    result = CategorySortingService.new(@books, params).call
Book

2019-01-31 18:44 UTC, dzemlianoi-double commented on app/controllers/categories_controller.rb
> +    @pagy, @books_category = pagy(result, items: 12)
Constant

2019-01-31 18:44 UTC, dzemlianoi-double commented on app/controllers/home_controller.rb
> +    @top_books = books.first(4)
4 to constant

2019-01-31 18:44 UTC, dzemlianoi-double commented on app/controllers/home_controller.rb
> +    @new_books = books.last(3)
3 to constant

2019-01-31 18:44 UTC, dzemlianoi-double commented on app/controllers/home_controller.rb
> +class HomeController < ApplicationController
rename ctrl

2019-01-31 18:44 UTC, dzemlianoi-double commented on app/controllers/home_controller.rb
> +    books = Book.all
don't get all books

2019-01-31 18:44 UTC, dzemlianoi-double commented on app/helpers/application_helper.rb
> +  include Pagy::Frontend
remove from here

2019-01-31 18:44 UTC, dzemlianoi-double commented on app/presenters/category_presenter.rb
> +    link_to 'All books', category_path('all_books')
all_books?

2019-01-31 18:44 UTC, dzemlianoi-double commented on app/presenters/category_presenter.rb
> +    params[:id] == 'all_books' ? 'All books' : categories.where(id: params[:id]).first.name
find_by

2019-01-31 18:44 UTC, dzemlianoi-double commented on app/services/category_sorting_service.rb
> +    @params = params
@current_sort = params[:sort_by]

2019-01-31 18:44 UTC, dzemlianoi-double commented on app/views/books/_book.html.haml
> +          = @current_book.description[0..100]
0..100?

2019-04-25 16:06 UTC, Svatok requested changes

2019-04-25 16:06 UTC, Svatok commented on app/forms/address_form.rb
> +  def create_address
Move this to service

2019-04-25 16:06 UTC, Svatok commented on app/services/checkout_show_service.rb
> +    case params[:step]
presenter_class = {
'address' => AddressPresenter,
...
}[params[:step]]
presenter_class.new(params: params, current_order: current_order)

2019-04-26 20:24 UTC, Svatok requested changes

2019-04-26 20:24 UTC, Svatok commented on app/services/checkout_update_service.rb
> +class CheckoutUpdateService
You should do something like this:
```ruby
SERVICES = {
  address: AddressService,
  delivery: DeliveryService,
  ...
}.freeze

def call
  return false unless step_available?
  service = SERVICES[params[:step].to_sym].new(params, current_user, current_order)
  service.call  
  @presenter = service.presenter
end

def step_available?
  # check if params[:step] valid and available
end
 
```

2019-04-26 20:24 UTC, Svatok commented on app/services/merge_items_cart_service.rb
> +  def add_current_order_session_user_id
you should have helper method `current_order` in ApplicationController instead of this

2019-04-26 20:24 UTC, Svatok commented on app/services/merge_items_cart_service.rb
> +  def change_items_order_id_to_current
This is a very strange method)

2019-04-26 20:26 UTC, Svatok requested changes

2019-04-26 20:26 UTC, Svatok commented on app/controllers/accounts_controller.rb
> +    account = User.find_by(id: params[:id].to_i)
Maybe `current_user.destroy` and remove his session?

2019-05-02 15:58 UTC, Svatok requested changes

2019-05-02 15:58 UTC, Svatok commented on app/controllers/application_controller.rb
> +  def home_page
Move to other controller

2019-05-02 15:58 UTC, Svatok commented on app/controllers/application_controller.rb
> +    MergeItemsCartService.new(Order.find_by(id: session[:current_order_id]), current_user).call
Please remove this service

2019-05-02 15:58 UTC, Svatok commented on app/controllers/line_items_controller.rb
> +    session[:current_order_id] = cart_service.create_order.id unless cart_service.check_create_order?(current_order)
```ruby
cart_service = CartCreateService.new(current_user, params_request, params)
cart_service.call(current_order)
session[:current_order_id] = cart_service.current_corder.id unless current_order
```

2019-05-02 15:58 UTC, Svatok commented on app/controllers/line_items_controller.rb
> +    session[:current_order_id] = cart_service.create_order.id unless cart_service.check_create_order?(current_order)
```ruby
order = current_order || Order.create(user: current_user)
```

2019-05-02 15:58 UTC, Svatok commented on app/controllers/orders_controller.rb
> +    @sort_orders = OrderSortingService.new(params, current_user).call
OrderDecorator.decorate_collection(OrderSortingService.new(params, current_user).call)

2019-05-02 15:58 UTC, Svatok commented on app/controllers/orders_controller.rb
> +    @order = Order.find_by(id: params[:id])
@order = Order.find_by(id: params[:id]).decorate

2019-05-02 15:58 UTC, Svatok commented on app/controllers/orders_controller.rb
> +  decorates_assigned :order
remove this

2019-05-02 15:58 UTC, Svatok commented on app/presenters/delivery_presenter.rb
> +    'fill_delivery'
CHECKOUT_STEPS = {
fill_delivery: 'fill_delivery',
...
}.freeze
CHECKOUT_STEPS[:fill_delivery]

2019-05-05 16:50 UTC, Svatok requested changes

2019-05-05 16:50 UTC, Svatok commented on app/presenters/books_presenter.rb
> +    Order.all.each do |order|
Please make this through `joins(:orders)` and `group`

2019-05-05 16:50 UTC, Svatok commented on app/presenters/cart_presenter.rb
> +    current_order.line_items.map { |item| item.quantity * item.book.price }.sum
current_order.line_items.sum { ... }

2019-05-05 16:50 UTC, Svatok commented on app/presenters/cart_presenter.rb
> +    current_order.line_items.find_by(book_id: book.id).quantity
find_by(book: book)

2019-05-05 16:50 UTC, Svatok commented on app/presenters/comment_presenter.rb
> +    Comment.where(book_id: current_book.id)
current_book.comments

2019-05-05 16:50 UTC, Svatok commented on app/presenters/comment_presenter.rb
> +    "#{t('book_page.comment.reviews')} (#{all_comments.where(book_id: @current_book.id).count})"
`all_comments.where(book_id: @current_book.id)` is unnecessary

2019-05-05 16:50 UTC, Svatok commented on app/presenters/comment_presenter.rb
> +    User.find_by(id: comment.user_id).email.first
fix

2019-05-05 16:50 UTC, Svatok commented on app/presenters/comment_presenter.rb
> +    User.find_by(id: comment.user_id).email
fix

2019-05-05 16:50 UTC, Svatok commented on app/presenters/current_book_presenter.rb
> +    current_book.description[0..current_book.description.length]
[0..current_book.description.length] is unnecessary

2019-05-05 16:50 UTC, Svatok commented on app/presenters/current_book_presenter.rb
> +    "H:#{@current_book.heigth}\" x W: #{@current_book.width}\" x D: #{@current_book.depth}"
without `@`

2019-05-05 16:50 UTC, Svatok commented on app/presenters/delivery_presenter.rb
> +    return true if current_order.delivery_id == id
only `current_order.delivery_id == id`

2019-05-05 16:50 UTC, Svatok commented on app/presenters/header_presenter.rb
> +    return 0 if !current_order || current_order.complete?
I think method `current_order` should not return completed order, so you can:
`current_order&.line_items&.map(&:quantity)&.sum.to_i`

2019-05-05 16:50 UTC, Svatok commented on app/presenters/payment_presenter.rb
> +    current_order.credit_card[type] if current_order.credit_card
`if current_order.credit_card` is unnecessary

In View use current_card&.some_attribute

2019-05-05 16:50 UTC, Svatok commented on app/services/address_checkout_service.rb
> +    create_or_update_checkout_addresses & true if @billing.valid? & @shipping.valid?
Do not use `&`.
` & true ` is unnecessary

2019-05-05 16:50 UTC, Svatok commented on app/services/address_checkout_service.rb
> +    create_or_update_address(@billing, current_order.addresses.billing)
without `@`, because you have attr_reader

2019-05-05 16:50 UTC, Svatok commented on app/services/cart_create_service.rb
> +    new_order ||= Order.new
Only `Order.create`

2019-05-05 16:50 UTC, Svatok commented on app/services/cart_create_service.rb
> +    LineItem.new(
current_order.line_items.create(...)

2019-05-05 16:50 UTC, Svatok commented on app/services/cart_create_service.rb
> +    @current_order = current_order
@order = current_order || create_order

2019-05-05 16:50 UTC, Svatok commented on app/models/order.rb
> +  has_one :coupon, dependent: :nullify
It is should be belongs_to :coupon, optional: true

2019-05-05 16:50 UTC, Svatok commented on app/services/checkout_show_service.rb
> +    current_order.address! & current_order.update(user_id: current_user.id)
&&

2019-05-05 16:50 UTC, Svatok commented on app/services/checkout_show_service.rb
> +    choose_presenter if choosen_step && choosen_step <= Order.statuses[current_order.status]
What will be if choosen_step is nil? Can that is be?

2019-05-05 16:50 UTC, Svatok commented on app/services/comment_service.rb
> +    comment = Comment.new(comment_form.attributes.without(:current_book, :current_user))
```
attributes = comment_form.attributes.without(:current_book, :current_user).merge(user_id: comment_form.current_user, book_id: comment_form.current_book)
Comment.create(attributes)
```

2019-05-05 16:50 UTC, Svatok commented on app/services/sorting_service.rb
> +    !params[:category_id] ? books : books_chosen_category
books_chosen_category.presence || books

2019-05-05 16:50 UTC, Svatok commented on app/views/carts/books/_books_for_phone.html.haml
> +            = "€#{book.price}"
i18

2019-05-05 16:50 UTC, Svatok commented on app/views/checkout/_confirm.html.haml
> +                = "€#{@cart_presenter.subtotal_prise_book(item.book)}"
i18

2019-05-05 16:51 UTC, Svatok reviewed
Rubocop!

2019-05-07 20:16 UTC, Svatok requested changes
Pleasse check cases:
https://bookstore-rostik.herokuapp.com/books?sort_by=hgfdggh
https://bookstore-rostik.herokuapp.com/orders/0
1. When i add comment i do not see any notification about success. Also i should not see my comment before it will be approved by admin.
2. Please add emails (sign up, change passsword)
3. Please add ability for adding several images to book
4. Admin should be able to change order state In Progress, In Delivery, Delivered, Canceled

2019-05-07 20:16 UTC, Svatok commented on spec/services/cart_create_service_spec.rb
> +      # expect(service.call(order)).to eq(true)
????

2019-05-07 20:16 UTC, Svatok commented on spec/services/comment_service_spec.rb
> +        # expect(service.save_comment).to eq(true)
????

2019-05-07 20:16 UTC, Svatok commented on spec/spec_helper.rb
> +SimpleCov.start do
move to rails_helper

2019-05-13 07:58 UTC, Svatok commented on app/presenters/books_presenter.rb
> +    top_books.map { |book| Book.find_by(id: book.first) }.first(COUNT_TOP_BOOKS)
Move `.first(COUNT_TOP_BOOKS)` to:
`top_books = Book.joins(:orders).group(:id).count.sort_by { |_, value| -value }.first(COUNT_TOP_BOOKS)`

2019-05-13 07:58 UTC, Svatok commented on app/services/cart_create_service.rb
> +    @order = current_order
What about case when current_order is nil?
We discussed that. Please revise that.

2019-05-13 07:58 UTC, Svatok commented on spec/services/comment_service_spec.rb
> +        service.save_comment
`expect { service.save_comment }.to change(Comment, :count).from(0).to(count_comment_after_create)`
Please do something like this in another similar specs

2019-05-13 07:58 UTC, Svatok commented on spec/services/delivery_service_spec.rb
>        expect(service.call).to eq(true)
expect { service.call }.to change { order.reload.delivery_id }.from(nil).to(delivery.id)

2019-05-14 19:43 UTC, Svatok reviewed
Please add title for all `it` specs: it 'some title' do ... end

2019-05-14 19:43 UTC, Svatok commented on spec/services/address_checkout_service_spec.rb
> +      expect { service.call }.to change(Address, :count).from(0).to(count_after_create)
also please add:
```ruby
expect(order.addresses.billing.first.first_name).to eq(order.addresses.shipping.first.first_name)	
expect(order.addresses.billing.first.phone).to eq(order.addresses.shipping.first.phone)	
```

2019-05-14 19:43 UTC, Svatok commented on spec/services/cart_create_service_spec.rb
> +      expect { service.call(order) }.to change(LineItem, :count).from(0).to(final_count_items)
also add:
```
expect(LineItem.second.book).to eq(book)
```

2019-05-14 19:43 UTC, Svatok commented on spec/services/cart_delete_service_spec.rb
> +      expect(LineItem.all).to eq([])
expect(LineItem.all).to be_empty

2019-05-14 19:43 UTC, Svatok commented on spec/services/checkout_update_service_spec.rb
>        expect(service.call).to eq(true)
```ruby
expect { service.call }.to change { address.reload.first_name }
  .from(address.first_name).to(valid_params_for_address[:billing_form][:first_name])
  .and change { address.reload.flast_name }.from(...).to(...)
  .and ...
```

2019-05-14 19:43 UTC, Svatok commented on spec/services/comment_service_spec.rb
> +        expect { service.save_comment }.to change(Comment, :count).from(0).to(count_comment_after_create)
also check comment attributes

2019-05-14 19:43 UTC, Svatok commented on spec/services/email_service_spec.rb
> +      expect { service.save }.to change { user.email }.from(user.email).to(params[:email])
change { user.reload.email }

2019-05-15 07:42 UTC, Svatok approved these changes

2019-05-15 11:41 UTC, merged